// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR0bAi4iNlCYNiDY1-0CFHHihEbLjCT6Y',
    appId: '1:824380979647:web:58af166c8e67c34b74c90a',
    messagingSenderId: '824380979647',
    projectId: 'login-auth-411c1',
    authDomain: 'login-auth-411c1.firebaseapp.com',
    storageBucket: 'login-auth-411c1.appspot.com',
    measurementId: 'G-WERBTD162L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkf7yOZRsqxvIQLh7kLPU2mAkq-dwU0rI',
    appId: '1:824380979647:android:085b7c26bc5d759474c90a',
    messagingSenderId: '824380979647',
    projectId: 'login-auth-411c1',
    storageBucket: 'login-auth-411c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGLIeL9rckBFXgQIfDpyqlhJ4-hCkBJ50',
    appId: '1:824380979647:ios:63eed47a54ae882374c90a',
    messagingSenderId: '824380979647',
    projectId: 'login-auth-411c1',
    storageBucket: 'login-auth-411c1.appspot.com',
    iosBundleId: 'com.example.loginauth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGLIeL9rckBFXgQIfDpyqlhJ4-hCkBJ50',
    appId: '1:824380979647:ios:8eef4d3379c9636474c90a',
    messagingSenderId: '824380979647',
    projectId: 'login-auth-411c1',
    storageBucket: 'login-auth-411c1.appspot.com',
    iosBundleId: 'com.example.loginauth.RunnerTests',
  );
}
